### ISSUE TITLE
Extremely slow performance rebuilding long list of rich rules

### ISSUE THREAD

**Issue by wzzrd** [firewalld/firewalld#849]
**What happened**:
I have fail2ban running with firewalld as a backend, using the fail2ban firewallcmd-rich-rules banaction.

I have quite a long set of banned IP addresses at this moment, over 8k of them, sigh. After rebooting my server - it's a mere rpi4 - it takes hours to rebuild the list of banned ip addresses back up in firewalld. All that time, the firewalld process is at about 100% CPU usage.

For the first couple of hours, the process is about 500 rules per 15 minutes, but then drops to about 100 per 15 minutes eventually.

**What you expected to happen**:
After reboot, rules are inserted quite quickly. Not taking hours, anway.

**How to reproduce it (as minimally and precisely as possible)**:
Try and re-insert a long list of firewalld rich rules. 

**Anything else we need to know?**:

**Environment**:
rpi4 with 8gib of ram.
fedora 34
fail2ban-0.11.2-6.fc34
firewalld-0.9.4-1.fc34

I'm not sure whether better performance can be expected, whether this is a problem with fail2ban or firewalld, but I'm filing the issue here first because of the high CPU usage by firewalld.

**Comment by cryptoluks** [comment]
Maybe related: I today tried to rebuilt one country ipset (whitelist, around 18k subnets), which also takes forever. Like hours probably. It worked with the same script several months ago really fast, but currently with firewalld 1.0.0 it is simply unusable.

So the rebuilding of your rich rules was faster at one point right? Even with 8k entries?

**Comment by erig0** [comment]
> **What happened**:
> I have fail2ban running with firewalld as a backend, using the fail2ban firewallcmd-rich-rules banaction.
> 
> I have quite a long set of banned IP addresses at this moment, over 8k of them, sigh. After rebooting my server - it's a mere rpi4 - it takes hours to rebuild the list of banned ip addresses back up in firewalld. All that time, the firewalld process is at about 100% CPU usage.

Is the rich rule set saved in firewalld's config? Or does it come from fail2ban at runtime?

**Comment by wzzrd** [comment]
I think

> > **What happened**:
> > I have fail2ban running with firewalld as a backend, using the fail2ban firewallcmd-rich-rules banaction.
> > I have quite a long set of banned IP addresses at this moment, over 8k of them, sigh. After rebooting my server - it's a mere rpi4 - it takes hours to rebuild the list of banned ip addresses back up in firewalld. All that time, the firewalld process is at about 100% CPU usage.
> 
> Is the rich rule set saved in firewalld's config? Or does it come from fail2ban at runtime?

I think fail2ban feeds the rich rules back to firewalld one by one as IPs are re-banned at startup time, leading to firewalld consuming a lot of CPU cycles.

Not sure if there is another way.

**Comment by erig0** [comment]
> > > **What happened**:
> > > I have fail2ban running with firewalld as a backend, using the fail2ban firewallcmd-rich-rules banaction.
> > > I have quite a long set of banned IP addresses at this moment, over 8k of them, sigh. After rebooting my server - it's a mere rpi4 - it takes hours to rebuild the list of banned ip addresses back up in firewalld. All that time, the firewalld process is at about 100% CPU usage.
> > 
> > 
> > Is the rich rule set saved in firewalld's config? Or does it come from fail2ban at runtime?
> 
> I think fail2ban feeds the rich rules back to firewalld one by one as IPs are re-banned at startup time, leading to firewalld consuming a lot of CPU cycles.

Do you know what fail2ban is actually doing? Can you show the rules that it's generating? It should be in the zone config.
```
# firewall-cmd --list-all-zones
```

> Edit: coming to think of it, I think it needs to be this way. Fail2ban needs to control the rule input, because it needs to control when rules expire and need to be deleted. If I would do `--runtime-to-permanent`, wouldn't fail2ban loose control over which rules are inserted.

Correct.

**Comment by wzzrd** [comment]
The output of `firewall-cmd --list-all-zones` is as follows:

```
FedoraServer (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: REMOVED
  ports: REMOVED
  protocols:
  forward: no
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule family="ipv4" source address="195.138.74.30" port port="ssh" protocol="tcp" reject type="icmp-port-unreachable"
        rule family="ipv4" source address="5.188.64.174" port port="ssh" protocol="tcp" reject type="icmp-port-unreachable"
        rule family="ipv4" source address="103.92.24.242" port port="ssh" protocol="tcp" reject type="icmp-port-unreachable"
        rule family="ipv4" source address="178.32.139.147" port port="ssh" protocol="tcp" reject type="icmp-port-unreachable"
        rule family="ipv4" source address="175.45.180.38" port port="ssh" protocol="tcp" reject type="icmp-port-unreachable"
        rule family="ipv4" source address="139.198.120.226" port port="ssh" protocol="tcp" reject type="icmp-port-unreachable"
```

There's a massive list of 8000+ rich rules, obviously not pasting them all here.

**Comment by erig0** [comment]
Awhile back we fixed a performance issue when applying a large amount of rich rules from the permanent/XML config. Maybe there is another instance of this for the runtime config.

**Comment by erig0** [comment]
It looks like fain2ban is using `firewall-cmd` directly, see https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/config/action.d/firewallcmd-rich-rules.conf.

`firewall-cmd` has a pretty abysmal start up time due to all python imports - mostly glib.
```
# time firewall-cmd --quiet --add-rich-rule="rule family=ipv4 source address=10.123.1.1 port port=ssh protocol=tcp reject type=icmp-port-unreachable"

real    0m0.261s
user    0m0.133s
sys     0m0.015s
```

Compare that to using gdbus directly:
```
# gdbus call --system --dest=org.fedoraproject.FirewallD1 --object-path /org/fedoraproject/FirewallD1 --method org.fedoraproject.FirewallD1.zone.addRichRule "public" "rule family=ipv4 source address=10.124.1.1 port port=ssh protocol=tcp reject type=icmp-port-unreachable" 0

real    0m0.063s
user    0m0.006s
sys     0m0.003s
```

That's about 200 ms overhead due to python!

I think you could adapt the fail2ban action to use `gdbus` or `dbus-send`.

**Comment by wzzrd** [comment]
Very interesting. I'll give this a shot layer this week. Thanks for looking into this!

**Comment by wzzrd** [comment]
Ok, I checked this, and though it probably helps a bit, it doesn't solve the problem. The process that is consuming CPU cycles is not firewall-cmd, it is firewalld itself. The screenshot below shows the output of `top`. I restarted firewalld (by rebooting the server) 13 hours before I took this screenshot. About ~7800 rules had been inserted at this point (out of 9600+).

I have just enabled firewalld debugging to see if something turns up in the logs.

**Comment by wzzrd** [comment]
So yes, there is throttling, and a lot of it. Hadn't expected that to be a problem, since the core temperature of the Pi is fairly normal (or at least, that's what I though). I've spun up a VM on my workstation with similar specs and it is done in no-time, and no slow down at all.

Seems to be a problem that lies in the pi, not in firewalld. Sorry for the noise.

**Comment by FabioPedretti** [comment]
It looks like a nftable issue: https://bugzilla.redhat.com/show_bug.cgi?id=1908127

**Comment by wzzrd** [comment]
Really? The RSS of firewalld is 77620KiB atm, after three hours of chugging along. Free memory is over 6GiB. No mentions of segfaults in dmesg.
